package com.study.test.entity;

public class TPosition extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.post_name
     *
     * @mbggenerated
     */
    private String postName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.id
     *
     * @return the value of t_position.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.id
     *
     * @param id the value for t_position.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.post_name
     *
     * @return the value of t_position.post_name
     *
     * @mbggenerated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.post_name
     *
     * @param postName the value for t_position.post_name
     *
     * @mbggenerated
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.note
     *
     * @return the value of t_position.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.note
     *
     * @param note the value for t_position.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}
