package com.study.test.mybatis;

import com.study.test.entity.TUserTest;

import java.util.List;

public interface TUserTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbggenerated
     */
    int insert(TUserTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbggenerated
     */
    TUserTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbggenerated
     */
    List<TUserTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserTest record);
}
